# Uncomment the next line to define a global platform for your project
# platform :ios, '13.1'

target 'KaAPIproj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# 전체 추가
pod 'KakaoSDK'
  # Pods for KaAPIproj

end
